close all, clear all
% this version will load in the deployment log and process each deployment
% within the specified time range. a table of median/mean spectra levels
% will be computed and appended to a table that is saved out each time so
% as not to lose any progress. data will be saved to a specific
% path/filename that is descriptive of all relevant parameters that can be
% adjusted
[data_basedir,procdata_basedir,gitpath] = setUpDrifterPaths(0,1);

do_raw_data = true;
do_bf_data = false; % bf part still needs to be updated
do_plots = true;

% limit the data to process to the following:
expt = '2023_Fall_Kelvin_Seamount'; % process only this experiment
drifters = []; % process only these drifters 
dateset_local = []; % process only between these times 
deployments =[];

overwrite_data = true; 

save_plots = false;  % save out figures as png and fig
save_to_ppt = true; % print figures to powerpoint 

avg_type = 'Median'; % what type of average accross time do I want ?

% el_plot = [-90:16:90]; % which elevations to plot from beamformer (choose from -90:2:90)

savefolderbase = fullfile(procdata_basedir,mfilename);
if ~isfolder(savefolderbase)
    mkdir(savefolderbase)
end

% the frequency bands to plot for integrated results 
fband = [
    1e3 2.5e3
    2.5e3 15e3
    ];

% fft size for the spectrogram calculations 
% this will not impact bf results because those are being loaded in from
% preprocessed data
do_resample = true;
fres = 100;
fs_resample = 55e3;

if do_resample
    fs_spec = fs_resample;
else
    fs_spec = 102400;
end
nfft_spec = 2^nextpow2(fs_spec/fres); %

driftlog_file = fullfile(gitpath,'drifter','TFO_Drifter_deployment_log.xlsx');
opts = detectImportOptions(driftlog_file);
driftlog = readtable(driftlog_file);
driftlog.SunriseUTC = datetime(driftlog.SunriseUTC, "ConvertFrom", "excel",'Format','HH:mm:SS');
driftlog.SunsetUTC = datetime(driftlog.SunsetUTC, "ConvertFrom", "excel",'Format','HH:mm:SS');

deploy_time = driftlog.DeployDateLocal + driftlog.DeployTimeLocal;
recover_time = driftlog.RecoverDateLocal + driftlog.RecoverTimeLocal;

% downselect to the desired processing set 
process_set = true(size(driftlog,1),1);
if ~isempty(deployments)
    process_set = ismember(driftlog.Deployment,deployments);
end
if ~isempty(drifters)
    process_set = ismember(driftlog.DrifterNumber,drifters)&process_set;
end
if ~isempty(expt)
    process_set = process_set&ismember(driftlog.ExperimentName,expt);
end
if ~isempty(dateset_local)
    isintime = deploy_time >= dateset_local(1) & recover_time <= dateset_local(2);
    process_set = process_set&isintime;
end
driftlog = driftlog(process_set,:);
deploy_time = deploy_time(process_set);
recover_time = recover_time(process_set);

freq = 0:28000;
NL_dB_0 = getWentzWindNoise(0, freq);
NL_dB_3 = getWentzWindNoise(3, freq);
NL_dB_6 = getWentzWindNoise(6, freq);

% start the parallel pool 
Nworkers = 8;
parpool(Nworkers)

if save_to_ppt
    pptx    = exportToPPTX('../tools/myTemplate.pptx', ...
            'Dimensions',[12 6], ...
            'Title','Long Term Spectra', ...
            'Author','MATLAB', ...
            'Subject','Automatically generated PPTX file', ...
            'Comments','This file has been automatically generated by exportToPPTX');

    pptx_bf    = exportToPPTX('../tools/myTemplate.pptx', ...
            'Dimensions',[12 6], ...
            'Title','Beamformer Output', ...
            'Author','MATLAB', ...
            'Subject','Automatically generated PPTX file', ...
            'Comments','This file has been automatically generated by exportToPPTX');
end

deployment_set = unique(driftlog.Deployment).';

for deployment = deployment_set
    Ssavefilename = []; Bsavefilename = [];

    % get the index of this deployment in the table
    didx = find(driftlog.Deployment==deployment,1,'first');

    t0_utc = deploy_time(didx) + hours(driftlog.TimeZoneOffset(didx));
    tend_utc = recover_time(didx) + hours(driftlog.TimeZoneOffset(didx));
    event_name = sprintf('Drifter%i_Acoustic%i_%s_%s',driftlog.DrifterNumber(didx),driftlog.AcousticSphere(didx),...
        datestr(t0_utc,'YYYYmmDDThhMMss'),...
        datestr(tend_utc,'YYYYmmDDThhMMss'));

    data_subdir = fullfile(driftlog.ExperimentName{didx},event_name);

    param_spec = sprintf('fs%1.0f_nfft%i',fs_spec,nfft_spec);

    thissavefolder = fullfile(savefolderbase,param_spec,driftlog.ExperimentName{didx});

    if ~isfolder(thissavefolder)
        mkdir(thissavefolder)
    end

    Ssavefilename = fullfile(thissavefolder,sprintf('Spectra_%s',event_name));

    Bsavefilename = fullfile(thissavefolder,sprintf('Beam_Spectra_%s',event_name));

    hx = []; hy = []; hz = []; hp = []; F = [];
    h1 = []; savename = []; beamdata = [];

    % get full path to this data set
    data_dir = fullfile(data_basedir,data_subdir,'AcousticData');
    [filelist,filetimes_utc] = getFilesInRange(data_dir,t0_utc,tend_utc);

    config_file = fullfile(data_dir,driftlog.AcousticConfig{didx});
    acoustic_config = readtable(config_file);
    ch_select = acoustic_config.Channel(~cellfun(@isempty,acoustic_config.sensor_type));

    % % select which processed result to use
    % proc_version = 'run_drifter_processing_v2';
    % array_type = 'line'; fs_bf = 55e3; nfft_bf = 1024; el_res = 2;
    % % procdata_dir = fullfile(procdata_basedir,data_subdir,proc_version,...
    % %     sprintf('%s_fs%1.0f_nfft%1.0f_dEl%i_T%s',array_type,fs_bf,nfft_bf,el_res,...
    % %     datestr(t0,'yyyymmdd_HHMMSS')),'processed_data');
    % procdata_dir = fullfile(procdata_basedir,data_subdir,proc_version,...
    %     sprintf('%s_fs%1.0f_nfft%1.0f_dEl%i',array_type,fs_bf,nfft_bf,el_res),'processed_data');

    % Spow_avg = zeros(length(filelist),nfft_bf/2+1,12);
    % Spow_med = zeros(length(filelist),nfft_bf/2+1,12);
    % b_incoh_avg_dB = zeros(length(filelist),91,size(fband,1));
    % b_incoh_med_dB = zeros(length(filelist),91,size(fband,1));
    % Bpow_avg = zeros(length(filelist),nfft_bf/2+1,91);
    % Bpow_med = zeros(length(filelist),nfft_bf/2+1,91);
    % Tfile = NaT(1,length(filelist));

    process_raw_data = do_raw_data&(~exist([Ssavefilename '.mat'],'file')|overwrite_data);
    process_bf_data = do_bf_data&(~exist([Bsavefilename '.mat'],'file')|overwrite_data);

    if process_raw_data || process_bf_data
       %for ifile = 1:length(filelist)
       Nfiles = length(filelist);
       Spow_avg = zeros(Nfiles,nfft_spec/2+1,length(ch_select));
       F_spec = zeros(Nfiles,nfft_spec/2+1);
       parfor (ifile = 1:length(filelist),Nworkers)
            savename = '';
            F = [];
            tic
            fprintf('Deployment %i: processing spectra for file %i of %i\n',deployment,ifile,length(filelist))

            % load in the raw data to get spectrograms?
            
            if process_raw_data
                wav_filename = fullfile(filelist(ifile).folder,filelist(ifile).name);
                [y,fs0] = audioread(wav_filename);
                if do_resample
                    y = resample(y,fs_spec,fs0);
                end

                
                [Spow,F_spec(ifile,:),T] = getDrifterSpectrogramV2(y,nfft_spec,[],fs_spec,config_file,'psd');

                % average over time
                Spow_avg(ifile,:,:) = squeeze(mean(Spow,2));
                Spow_med(ifile,:,:) = squeeze(median(Spow,2));

                % if 1 % save as we go 
                %     parsaveS(Ssavefilename,Spow_avg,Spow_med,F_spec,fband,Tfile)
                % end

                % if 0 
                %     figure
                %     plot(F_spec(:,1)/1e3,10*log10(squeeze(Spow_avg(ifile,:,8)))); grid on; ylim auto
                %     keyboard
                % end
            end

            % load beamformed data? this still needs to be updated,
            % requires saved beamform data
            
            if process_bf_data
                
                savename = sprintf('beamformer_data_%s.mat',datestr(filetimes_utc(ifile),'yyyymmddTHHMMSS'));
                beamfile_name = fullfile(procdata_dir,savename);
                file_exists = exist(beamfile_name,'file');
                if file_exists

                    beamdata = load(beamfile_name,'beamdata');
                    beamdata = beamdata.beamdata;
                    beamdata = integrateBandBF(beamdata,fband);
                    % scale to match PSD units
                    % for some reason I thought it was a good idea to not save all
                    % the frequencies ... this is a patch...
                    % F_bf = [0:(nfft_bf/2)]*fs_bf/nfft_bf;
                    % Bpow = zeros(nfft_bf/2+1,length(beamdata.T_utc),91);
                    % [~,fidx] = intersect(F_bf,beamdata.F);
                    % Bpow(fidx,:,:) = 10.^(double(beamdata.B_pow_dB)/10)*(1/(winPow*fs_bf));
                    % Bpow= 10.^(double(beamdata.B_pow_dB)/10)*(1/(winPow*fs_bf));
                    Bpow = beamdata.B_pow*(1/(winPow*fs_bf));
                    df = median(diff(beamdata.F));
                    B_incoh = beamdata.B_incoh*(df/(winPow*fs_bf));

                    Bpow_avg(ifile,:,:) = mean(Bpow,2);
                    Bpow_med(ifile,:,:) = median(Bpow,2);

                    b_incoh_avg_dB(ifile,:,:) = 10*log10(squeeze(mean(B_incoh,1)));
                    b_incoh_med_dB(ifile,:,:) = 10*log10(squeeze(median(B_incoh,1)));
                else
                    fprintf('Deployment %i: BF file %i of %i, %s does not exist!\n',deployment,ifile,length(filelist),savename)
                end   
            end
            Tfile(ifile) = filetimes_utc(ifile);
            
            tdur=toc;
            
            fprintf('Deployment %i: file %i of %i took %1.2f seconds\n',deployment,ifile,length(filelist),tdur)
       end
        
        if process_raw_data
            parsaveS(Ssavefilename,Spow_avg,Spow_med,F_spec(1,:),fband,Tfile)
        end
        if process_bf_data
            el_res = 2;
            elev_deg = -90:el_res:90;
            F_bf = [0:(nfft_bf/2)]*fs_bf/nfft_bf;
            parsaveB(Bsavefilename,Bpow_avg,Bpow_med,b_incoh_avg_dB,b_incoh_med_dB,F_bf,fband,Tfile,elev_deg)
        end
    end
%%

if do_plots
    if save_to_ppt 
        title_slide = sprintf('Drifter #%i, Acoustic Sphere %i: %s',...
            driftlog.DrifterNumber(didx),driftlog.AcousticSphere(didx), driftlog.VectorSensor{didx});
        subtitle_slide = sprintf('%s - %s',t0_utc,tend_utc);

        pptx.addSlide('Master',1,'Layout','Title Slide');
        pptx.addTextbox(title_slide,'Position','Title');
        pptx.addTextbox(subtitle_slide,'Position','Subtitle');

        pptx_bf.addSlide('Master',1,'Layout','Title Slide');
        pptx_bf.addTextbox(title_slide,'Position','Title');
        pptx_bf.addTextbox(subtitle_slide,'Position','Subtitle');
    end
    % plot Wentz curve 
    figure
    plot(freq/1e3,NL_dB_0,'linewidth',2)
    hold on
    plot(freq/1e3,NL_dB_3,'linewidth',2)
    grid on
    xlabel('Freq, kHz')
    ylabel('Noise Level, dB re 1\muPa^2/Hz')
    legend('Sea State 0','Sea State 3')
    set(gca,'fontweight','bold','fontsize',14);
    title('Wentz Noise')
    

    % load in the saved results 
    if do_raw_data
        ssave = load(Ssavefilename,'Spow_avg','Spow_med','Tfile','F');
        Tfile = ssave.Tfile; F_spec_plot=ssave.F;
        Spow_avg = ssave.Spow_avg; Spow_med = ssave.Spow_med;
    end
    if do_bf_data
        bsave = load(Bsavefilename,'Bpow_avg','Bpow_med','b_incoh_dB','Tfile','fband','elev_deg','F');
        Bpow_avg = bsave.Bpow_avg; Bpow_med = bsave.Bpow_med;
        Tfile = bsave.Tfile; elev_deg = bsave.elev_deg; F_bf=bsave.F;
    end

    %% 
    % compute the in-band noise levels for wentz
    legend_str = cell(size(fband,1),1);
    for iband = 1:size(fband,1)
        fidx = freq>=fband(iband,1) & freq<=fband(iband,2);
        dfNL = median(diff(freq));
        NL0_band(iband) = 10*log10(sum(10.^(NL_dB_0(fidx)/10)));
        NL3_band(iband) =  10*log10(sum(10.^(NL_dB_3(fidx)/10)));
        NL6_band(iband) =  10*log10(sum(10.^(NL_dB_6(fidx)/10)));
    % 
        legend_str{iband} = sprintf('%1.2fkHz-%1.2fkHz',fband(iband,1)/1e3,fband(iband,2)/1e3);
    end


    % load the drifter ctd info
    % ctd = loadCTDData(Tfile,data_basedir);

    % load the IMU data
    % imu = loadIMUData(Tfile,data_dir);

    % load the USBL data
    logdir = fullfile(data_basedir,data_subdir,'ControlSystem');
    [driftcam,control_label] = loadDrifterLogDataV2(Tfile,logdir,driftlog.DrifterNumber(didx));
    %%
    ax = [];
    if do_raw_data
        switch avg_type
            case 'Median'
                Spowplot = Spow_med;
            case 'Mean'
                Spowplot = Spow_avg;
        end

        sensor_to_plot = 1:size(Spowplot,3);

        rawdata_legend_str = {};
        for sensID = sensor_to_plot

            max_F = min(max(F_spec_plot/1e3),15);

            figure('Renderer','zbuffer'); 
            ssize = get(groot, 'ScreenSize'); 
            set(gcf, 'Position', ssize);

            tiledlayout(5,1);
            ax(end+1) = nexttile;

            driftcamStatusPlot(driftcam,control_label,driftlog.SunsetUTC(didx),driftlog.SunriseUTC(didx));

            ax(end+1) = nexttile([4 1]);
            pcolor(Tfile,F_spec_plot/1e3,10*log10(Spowplot(:,:,sensID)).'); shading flat
            colormap jet
            colorbar
            ylim([0 max_F])
            clim([20 90])
            set(gca,'fontweight','bold','fontsize',14);
            set(gca,'XTickLabelRotation',90)
            ax2 = gca; ax2.XTick = linspace(Tfile(1),Tfile(end),80);
            ax(end+1) = ax2;
            datetick('x','mm-dd, HH:MM:SS','keepticks')

            ch_str = sprintf('CH%i %s',ch_select(sensID),acoustic_config.sensor_type{ch_select(sensID)});
            rawdata_legend_str = cat(2,rawdata_legend_str,ch_str);
            sgtitle(sprintf('%s: One Minute %s Spectrogram',ch_str,avg_type),'fontweight','bold','fontsize',18)

            
            ax2.YTick = 0:0.1*max_F:max_F;
            ylabel('Freq, kHz')

            linkaxes(ax,'x')
            xlim([min(Tfile) max(Tfile)])

            if save_to_ppt
                
                slideId = pptx.addSlide();
                fprintf('Added slide %d\n',slideId);
                pptx.addTextbox([title_slide ' ' subtitle_slide ch_str]);
                pptx.addPicture(gcf);
            end
        end

        % make line plots of in-band noise levels 
        figure('Renderer','zbuffer'); 
        ssize = get(groot, 'ScreenSize'); 
        set(gcf, 'Position', ssize);
        tiledlayout(size(fband,1),1)

        for iband = 1:size(fband,1)
            fidx = F_spec_plot>=fband(iband,1) & F_spec_plot<=fband(iband,2);
            Spow_incoh_dB = squeeze(10*log10(trapz(F_spec_plot(fidx),Spowplot(:,fidx,:),2)));
            % ax(end+1)=subplot(size(fband,1),1,iband);
            ax(end+1) = nexttile;
            h1=plot(Tfile,Spow_incoh_dB,'linewidth',2);
            hold on
            % hp=plot(Tfile,Spow_incoh_dB(:,9),'--','linewidth',2);
            % hx=plot(Tfile,Spow_incoh_dB(:,10),'--','linewidth',2);
            % hy=plot(Tfile,Spow_incoh_dB(:,11),'--','linewidth',2);
            % hz=plot(Tfile,Spow_incoh_dB(:,12),'--','linewidth',2);
            plot(Tfile,NL0_band(iband).*ones(length(Tfile),1),'-.k')
            plot(Tfile,NL3_band(iband).*ones(length(Tfile),1),'-.k')
            grid on
            ylim([60 100])

            set(gca,'fontweight','bold','fontsize',14);
            ylabel('NL, dB re 1\muPa')
            title( legend_str{iband})
            ax2 = gca(); ax2.XTick = linspace(Tfile(1),Tfile(end),80);
            ax2.XTickLabel = '';

        end
        ax2 = gca(); ax2.XTick = linspace(Tfile(1),Tfile(end),80);

        legend(nexttile(1),h1,rawdata_legend_str,'location','northeastoutside ')

        sgtitle('Single Channel Noise Levels','fontweight','bold','fontsize',18)

        if save_plots 
            saveas(gcf,fullfile(Ssavefilename),'fig')
            saveas(gcf,fullfile(Ssavefilename),'png')
        end

    end
    linkaxes(ax,'x')
    if do_bf_data
        switch avg_type
            case 'Median'
                Bpow = Bpow_med;
            case 'Mean'
                Bpow = Bpow_avg;
        end

        % make color plots for select elevations 
        
        for iel = el_plot
            figure('Renderer','zbuffer'); 
            ssize = get(groot, 'ScreenSize'); 
            set(gcf, 'Position', ssize);

            tiledlayout(6,1);

            ax(end+1) = nexttile;
          
            driftcamStatusPlot(driftcam,control_label,sunset_app_utc,sunrise_app_utc);

            ax(end+1) = nexttile;
            

            ax(end+1) = nexttile([4 1]);

            elidx = elev_deg==iel;
            pcolor(Tfile,F_bf/1e3,10*log10(Bpow(:,:,elidx)).'); shading flat
            colormap jet
            colorbar
            ylim([0 max(F_bf/1e3)])
            caxis([30 90])
            set(gca,'fontweight','bold','fontsize',14);
            
            set(gca,'XTickLabelRotation',90)
            ax2 = gca(); ax2.XTick = linspace(Tfile(1),Tfile(end),80);
            ax(end+1) = ax2;
            
            max_F = min(max(F_bf/1e3),15);
            ax2.YTick = 0:0.1*max_F:max_F;
            ylabel('Freq, kHz')
            

            sgtitle(sprintf('One Minute %s Beamformer Output: El=%1.2f deg',...
                avg_type,elev_deg(elidx)),'fontsize',18,'fontweight','bold')

            if save_to_ppt
                linkaxes(ax,'x')
                xlim([min(Tfile) max(Tfile)])
                slideId = pptx_bf.addSlide();
                fprintf('Added slide %d\n',slideId);
                pptx_bf.addPicture(gcf);
                pptx_bf.addTextbox([title_slide ' ' subtitle_slide sprintf(' Elev %1.0f',elev_deg(elidx))]);

            end

            figure('Renderer','zbuffer'); 
            ssize = get(groot, 'ScreenSize'); 
            set(gcf, 'Position', ssize);

            tiledlayout(5,1);

            ax(end+1) = nexttile;
            
            driftcamStatusPlot(driftcam,control_label,sunset_app_utc,sunrise_app_utc);

            ax(end+1) = nexttile([4 1]); B_incoh_dB = [];
            for iband = 1:size(fband,1)
                fidx = F_bf>=fband(iband,1) & F_bf<=fband(iband,2);
                B_incoh_dB(:,:,iband) = squeeze(10*log10(trapz(F_bf(fidx),Bpow(:,fidx,:),2)));
            end
            h=plot(Tfile,squeeze(B_incoh_dB(:,elev_deg==0,:)),'linewidth',2);
            hold on
            set(gca,'ColorOrderIndex',1)
            plot(Tfile,NL0_band.*ones(length(Tfile),1),'--')
            set(gca,'ColorOrderIndex',1)
            plot(Tfile,NL3_band.*ones(length(Tfile),1),'-.')
            grid on
            legend(h,legend_str)
            set(gca,'fontweight','bold','fontsize',14);
            ylabel('NL, dB re 1\muPa')
            ylim([60 100])
            ax2 = gca(); ax2.XTick = linspace(Tfile(1),Tfile(end),80);
            ax2.XLabel.Visible = 'off';
            datetick('x','mm-dd, HH:MM:SS','keepticks')
            ax2.XTickLabelRotation = 90;

            sgtitle(sprintf('Beamformed Output, Elev = %1.2f deg',iel),'fontweight','bold','fontsize',18)



        end
        linkaxes(ax,'x')
            % saveas(gcf,fullfile(Bsavefilename),'fig')
            % saveas(gcf,fullfile(Bsavefilename),'png')
%%
            figure('Renderer','zbuffer'); 
            ssize = get(groot, 'ScreenSize'); 
            set(gcf, 'Position', ssize);

            tiledlayout(2*size(fband,1)+1,1)

            ax(end+1) = nexttile;

            driftcamStatusPlot(driftcam,control_label,driftlog.SunsetUTC(didx),driftlog.SunriseUTC(didx));

          

            for iband = 1:size(fband,1)

                % ax2=subplot(size(fband,1),1,iband);
                ax(end+1) = nexttile([2,1]);
                pcolor(Tfile,elev_deg,B_incoh_dB(:,:,iband).'); shading flat
                colormap jet
                cb = colorbar;
                clim([70 90])
                set(gca,'fontweight','bold','fontsize',14);
                cb.Label.String = 'NL, dB re 1\muPa';
                title( legend_str{iband})
                ylabel('Elevation, deg')
                ax2 = gca; ax2.XTick = linspace(Tfile(1),Tfile(end),80);
                ax2.XTickLabel = '';
                


            end
            ax2.XTick = linspace(Tfile(1),Tfile(end),80);
            datetick('x','mm-dd, HH:MM:SS','keepticks')
            ax2.XTickLabelRotation = 90;
            
            sgtitle( sprintf('Beamformer Output, One Minute %s', avg_type),'fontweight','bold','fontsize',18)
            
            if save_to_ppt
                linkaxes(ax,'x')
                xlim([min(Tfile) max(Tfile)])
                slideId = pptx_bf.addSlide();
                fprintf('Added slide %d\n',slideId);
                pptx_bf.addPicture(gcf);
                pptx_bf.addTextbox([title_slide ' ' subtitle_slide ch_str]);

            end
    end
    


    linkaxes(ax,'x')
    xlim([min(Tfile) max(Tfile)])
end

% close all

end

%% Save presentation and close presentation -- overwrite file if it already exists
% Filename automatically checked for proper extension
if save_to_ppt
    newFile     = pptx.save('long_term_spectra');
    newFile2     = pptx_bf.save('beamform_output');
end



function parsaveS(fname,Spow_avg,Spow_med,F,fband,Tfile)
save([fname '.mat'], 'Spow_avg','Spow_med','F','fband','Tfile')
end
function parsaveB(fname,Bpow_avg,Bpow_med,b_incoh_avg_dB,b_incoh_med_dB,F,fband,Tfile,elev_deg)
save([fname '.mat'], 'Bpow_avg','Bpow_med','b_incoh_avg_dB','b_incoh_med_dB','F','fband','Tfile','elev_deg')
end

