close all
clear all

use_remote = false;
addpath(genpath('../')) % add the ThodeLab GiT repo to path
[data_basedir,procdata_basedir,gitpath] = setUpDrifterPaths(use_remote,0);
data_basedir = '/Volumes/Shared/';

do_processing = true; % if saved beamformer data doesn't exist, process the data
% do_vs_processing = true; % if saved avs data doesn't exist, process the data
do_stats = true; % if true, compute the histograms
% overwrite_avs_data = false;
overwrite_beam_data =false;
overwrite_stats = true;
save_data = true; % if this is set to true, we will save bf and avs data

max_plot_time_hrs = 30;%16;

% limit the data to process to the following:
% expt = ''; % process only this experiment
% drifters =[]; % process only these drifters
dateset_local = []; % process only between these times
ch_select = 60:65;
array_type = 'line_60_1_65';
% ch_select = 123:128;
% array_type = 'line_123_1_128';
% ch_select = 1:128;
% array_type = 'line_1_1_128';

deployment_set = [2];
deployment_folder = { 
    'RAVA13_D1_sio'
    'RAVA13_D2_sio'
    'RAVA13_D3_sio'};
expt_name = 'NESMA24';

% time_to_process = [datetime(2024,7,17,11,0,0) datetime(2024,7,17,16,0,0)];
time_to_process = []; %[datetime(2024,7,22,23,0,0) datetime(2024,7,23,4,0,0)];

%% plot settings
save_to_ppt = false; % save the figures in a powerpoint file
save_figures = true; % save the figures out as png and fig files
do_histogram_plots = true; % if true, make the histogram plots as the data is processed

if do_histogram_plots
    % initialize the figures
    ssize = get(groot, 'ScreenSize');
%     az_hist_fig=figure; set(gcf, 'Position', ssize);
    el_hist_fig=figure; set(gcf, 'Position', ssize);
end
%% vertical array settings

el_res = 1;
time_avg=0.1; %Averaging time in seconds for beamformer output

% if true, only process the frequencies that correspond to frequencies in fband
only_bf_bands = false; 

%  Note: it is much faster to have multiple small bandwidths (<= 3 kHz)
%   than a few large bandwidths: keeps memory manageable, and one can
%   always combine smaller bandwidths together in later analysis.
%   Each 3 kHz bandwidth adds 3 seconds to processing time.
bf_fband = 3e3; % divide bf processing up into bands of this size
% i used 500 for the full 128 element array, 3kHz for the smaller 6 element
% subsets

%%%Frequency bands for histogram processing , this is independent of bands
%%%used for beamformer
fband = [
    500 1.5e3
    2.5e3 7e3;
    9e3 25e3;
  ];

% histogram edges/(grids in degrees)
%elev_deg = -90:el_res:90;

%%%Option for elevation that has denser sampling close to the horizontal
% elev_deg=asind(linspace(-1,1,1+(180/el_res)));
% elev_deg=0.125*round(elev_deg/0.125);
elev_deg = -90:0.5:90;

% hist_param.az_edges = -0.5:2:360.5;
hist_param.el_edges = -90.5:el_res:91.5;


%% freq settings
do_resample = false;
do_filter = false; % filter first in the time domain?

fres = 100; % frequency resolution of FFT in Hz
prcnt_overlap =0; % percent overlap to use in spectrogram calculation
fs_resample = 51200;

%%%%File location settings
powerpoint_template = fullfile(gitpath,'tools','myTemplate.pptx');

% driftlog_file = fullfile(gitpath,'drifter','TFO_Drifter_deployment_log.xlsx');

% driftlog = getDeployLog(gitpath);

% downselect to the desired processing set
% process_set = true(size(driftlog,1),1);
% if ~isempty(deployments)
%     process_set = ismember(driftlog.Deployment,deployments);
% end
% if ~isempty(drifters)
%     process_set = ismember(driftlog.DrifterNumber,drifters)&process_set;
% end
% if ~isempty(expt)
%     process_set = process_set&ismember(driftlog.ExperimentName,expt);
% end
% if ~isempty(dateset_local)
%     isintime = deploy_time >= dateset_local(1) & recover_time <= dateset_local(2);
%     process_set = process_set&isintime;
% end
% driftlog = driftlog(process_set,:);

% deployment_set = unique(driftlog.Deployment).';




if save_to_ppt
    pptx    = exportToPPTX(powerpoint_template, ...
        'Dimensions',[12 6], ...
        'Title','Directionality Histograms', ...
        'Author','MATLAB', ...
        'Subject','Automatically generated PPTX file', ...
        'Comments','This file has been automatically generated by exportToPPTX');

end


if do_resample
    fs = fs_resample;
else
    fs = 25000;
end
nfft = 2^nextpow2(fs/fres); %
% overlap to use in spectrogram 
noverlp = floor(nfft*prcnt_overlap);

in2m = 0.0254;

for deployment = deployment_set
    % plot the dives separately
%     dive_index = find(driftlog.Deployment ==deployment).';
%     drifter_num = driftlog.DrifterNumber(dive_index(1));
    event_name = deployment_folder{deployment};
%     t0_utc = driftlog.DeployTimeUTC(dive_index(1));
%     tend_utc = driftlog.RecoverTimeUTC(dive_index(1));
    
% 
%     sunrise_app_utc = driftlog.SunriseUTC(dive_index(1));
%     sunset_app_utc = driftlog.SunsetUTC(dive_index(1));

    datasubdir = fullfile(data_basedir,expt_name,event_name);

    savefolder = fullfile(procdata_basedir,mfilename,...
        sprintf('%s_fs%1.0f_nfft%1.0f_noverlp%1.0f_dEL%i',array_type,fs,nfft,noverlp,el_res),...
       expt_name,event_name);

    if ~isfolder(savefolder)
        mkdir(savefolder)
    end

    % load the USBL data
%     driftcam = loadDrifterLogDataV2([t0_utc tend_utc],fullfile(datasubdir,'ControlSystem'),drifter_num);
    data_dir = fullfile(data_basedir,expt_name,'AcousticData',event_name);
%     [filelist,filetimes_utc] = getFilesInRange(data_dir,t0_utc,tend_utc);
    filelist_full = dir(fullfile(data_dir,'*.sio'));
%     logdir = fullfile(data_basedir,data_subdir,'ControlSystem');
    filenames_full = vertcat(filelist_full.name);
    % Extract parts
%     timenames = extractBetween(filenames,'.','.');
    YYYY = 2000+str2num(filenames_full(:,8+(1:2)));      % Extract full 4-digit year
    DDD = str2num(filenames_full(:,8+(3:5)));       % Extract Julian day
    HH = str2num(filenames_full(:,8+(6:7)));        % Extract Hour
    MM = str2num(filenames_full(:,8+(8:9)));      % Extract Minute
    SS = str2num(filenames_full(:,8+(10:11)));      % Extract Second

    % Convert Julian day to datetime
    filetimes_utc = datetime(YYYY, 1, 1, HH, MM, SS) + days(DDD - 1);

    if ~isempty(time_to_process)
        include_files = filetimes_utc >=time_to_process(1) & filetimes_utc <= time_to_process(2);
    else
        include_files = true(size(filetimes_utc));
    end

    filetimes_utc = filetimes_utc(include_files);
    filenames_full = filenames_full(include_files);
    filelist_full = filelist_full(include_files);

    t0_utc = filetimes_utc(1);
    tend_utc = filetimes_utc(end);
    
    acoustic_dir = fullfile(datasubdir,'AcousticData');
    acoustic_files = dir(fullfile(acoustic_dir,'drifter*.wav'));

    config_file = dir(fullfile(data_dir,'acoustic_config_*.txt'));
    config_file = fullfile(config_file.folder,config_file.name);
    acoustic_config = readtable(config_file);
    acoustic_config = acoustic_config(ch_select,:);

%     for di = dive_index
        T_utc_save = [];

%         dive_time_start_utc = driftlog.TimeLastSatUTC(di);
%         if isnat(dive_time_start_utc)&& di==min(dive_index)
%             dive_time_start_utc = driftlog.DeployTimeUTC(di);
%         end
%         dive_time_stop_utc = driftlog.TimeFirstSatUTC(di);
%         if isnat(dive_time_stop_utc) && di==max(dive_index)
%             % if there was no dive end time, just use the recover time
%             dive_time_stop_utc = driftlog.RecoverTimeUTC(di);
%         end

%         vector_sensor = driftlog.VectorSensor{di};
%         acoustic_num = driftlog.AcousticSphere(di);

        

        
        dive_duration_hrs = hours(tend_utc - t0_utc);
        if  dive_duration_hrs > max_plot_time_hrs 
            % this plot and histogram object will be too large, split it up
            % into parts to process separately 
            Nparts = ceil(dive_duration_hrs/max_plot_time_hrs);
            parts_time_start_utc = t0_utc + hours(max_plot_time_hrs*(0:(Nparts-1)));
            parts_time_stop_utc = t0_utc + hours(max_plot_time_hrs*(1:(Nparts-1)));
            % the last time should alwasy be the end of the dive
            parts_time_stop_utc = [parts_time_stop_utc tend_utc];
        else 
            Nparts = 1;
            parts_time_start_utc = t0_utc;
            parts_time_stop_utc = tend_utc;
        end
        for ni = 1:Nparts
            
            time_start_utc = parts_time_start_utc(ni);
            time_stop_utc = parts_time_stop_utc(ni);

            this_event_name = sprintf('VLA_Deployment_%i_%s_%s',deployment,...
                datestr(time_start_utc,'YYYYmmDDThhMMss'),...
                datestr(time_stop_utc,'YYYYmmDDThhMMss'));

            bf_hist_filename = fullfile(savefolder,[this_event_name '_bf_hist.mat']);
%             avs_hist_filename = fullfile(savefolder,[this_event_name '_avs_hist.mat']);
        
%        [filelist,file_time_utc,filenames] = getFilesInRange(acoustic_files,time_start_utc,time_stop_utc);
          in_range = filetimes_utc>=time_start_utc & filetimes_utc<= time_stop_utc;
          filelist = filelist_full(in_range);
          file_time_utc = filetimes_utc(in_range);
          filenames = filenames_full(in_range,:);
            Nfiles = length(filelist);


%         azi_hist = zeros(Nfiles,length(hist_param.az_edges)-1,size(fband,1));
        elev_hist = single(zeros(Nfiles,length(hist_param.el_edges)-1,size(fband,1)));
        t_utc = NaT(1,Nfiles);

        tabs_files=datenum(file_time_utc);  %%%ALISON, CAN YOU FIX THIS?

        % now loop through the files found for this dive
        for file_idx = 1:Nfiles
            tic
            fprintf('\nProcessing file %i of %i: %s\n',file_idx,Nfiles,filelist(file_idx).name)

            bfsavename = sprintf('beamformer_data_%s.mat',datestr(file_time_utc(file_idx),'yyyymmddTHHMMSS'));
            bfsavename = fullfile(savefolder,'beamformer_data',bfsavename);
            bffile_exists = exist(bfsavename,'file');

%             vssavename = sprintf('avs_data_%s.mat',datestr(file_time_utc(file_idx),'yyyymmddTHHMMSS'));
%             vssavename = fullfile(savefolder,'avs_data',vssavename);
%             vsfile_exists = exist(vssavename,'file');

            if ~isfolder(fullfile(savefolder,'beamformer_data'))
                mkdir(fullfile(savefolder,'beamformer_data'))
            end
%             if ~isfolder(fullfile(savefolder,'avs_data'))
%                 mkdir(fullfile(savefolder,'avs_data'))
%             end

            % only load the data if we are going to process or reprocess
            if (do_processing&&((~bffile_exists||overwrite_beam_data)))
                % load the data and process
                fprintf('Loading data..\n')

                filename = fullfile(fullfile(filelist(file_idx).folder,filelist(file_idx).name));
                try
                    y = sioread(filename,1,0,ch_select);
                    fs00 = 25e3;
                catch
                    warning('Error reading file, skipping file %s',filename)
                    continue
                end
                disp('Data loaded');
                toc

%                 t_utc = file_time_utc(file_idx):seconds((1/fs00)):(file_time_utc(file_idx) + seconds(size(y0,1)-1)/fs00);
%                 t_sec0 = convertTo(t_utc,'posixtime'); %t_sec = t_sec - t_sec(1);

                if do_resample
                    %tic
                    % [y,t_sec] = resample(y0,t_sec0,fs);
                    % toc
                    disp('Decimation started')

                    R=round(fs00/fs);
                    sizz=size(y0);
                    sizz(1)=floor(sizz(1)/2);
                    for II=1:sizz(2)
                        y(:,II)=decimate(y0(:,II),R);
                    end
                    disp('Decimation done')
                    toc

                    clear y0 
                else
                    if fs00~=fs
                        error("wrong sample rate!")
                    end
                end
                if do_filter
                    [bb,aa]= butter(2,2*[f1 f2]/fs);
                    y = filter(bb,aa,y);

                end

                % compute the spectrogram of each channel
                k = 0;
				disp('compute FFT')
                [S,F,T,~,~,pos] = getDrifterSpectrogramV2(y,nfft,noverlp,fs,acoustic_config,'stft');
				disp('FFT done')
                toc
                T_utc = file_time_utc(file_idx) + seconds(T);

                clear y

            end

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%%Vertical beamforming option%%%%%%%%%%
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            if bffile_exists&&do_processing
                fprintf('Beamform Data Exists in: %s\n',bfsavename)
            end
            % if the file doesn't exist, or if we are overwriting the data
            % run the freq domain beamformer
            if do_processing&&(~bffile_exists||overwrite_beam_data)
                fprintf('Running Beamformer: %s\n',bfsavename)

%                 switch array_type
%                     case 'line'
% %                         bf_array_idx = [1 4 5 6 7 8];
%                         bf_array_idx = 1:size(S,3);
%                     otherwise
%                         error('Array type not defined')
%                 end

                %%%AARON: remove frequencies we don't care about.
                if only_bf_bands 
                    Ifreq=[];
                    for Iband=1:size(fband,1)
                        Ifreq=[Ifreq; find(F>=fband(Iband,1)&F<=fband(Iband,2))];
                    end
                    Ifreq=unique(Ifreq);  %Remove overlaps between frequency bands;
                else
                    Ifreq = 1:length(F);
                end
             
                %%%Run conventional beamformer, averaging over time_avg
                %%%intervals in time, and summing over frequency_bands
                %%%defined by fband
                [B_pow,Fout,Tout] = beamform_from_spec_avg(...
                    S(Ifreq,:,:),T,F(Ifreq),0,elev_deg,...
                    pos,[],bf_fband,time_avg);

                beamdata.kscale = 100;
                beamdata.B_pow_dB = uint16(beamdata.kscale*10*log10(B_pow));
                beamdata.F=Fout;
                beamdata.T_utc = file_time_utc(file_idx) + seconds(Tout);
                beamdata.elev_deg = elev_deg;

                toc
                disp('Beamformer done.')
                
                if save_data
                    disp('Saving beamformer data...')
                    save(bfsavename,'beamdata')
                    disp('Save complete.')
                    toc
                end

            elseif do_stats&&do_processing&&bffile_exists&&(~exist(bf_hist_filename,'file')||overwrite_stats)
                disp('Loading beamformer data...')
                load(bfsavename,'beamdata');
                toc
                disp('Load complete.')
            end  %%Beamforming

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%%%%%vector_sensor_processing
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            
           

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%Accumlated statistics from raw metrics%%%
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

            
            if do_stats
                if do_processing&&(overwrite_stats||~exist(bf_hist_filename,'file'))
                    disp('Starting beamformer histogram processing...')
                    if bffile_exists&&~overwrite_beam_data
                        % we need to get the power in linear units if we
                        % don't already have it in memory
                        if ~isfield(beamdata,'kscale')
                            beamdata.kscale = 1;
                        end
                        B_pow = 10.^(double(beamdata.B_pow_dB)/(beamdata.kscale*10));
                    end
                    bin_width = median(diff(hist_param.el_edges));
                    el_centers = hist_param.el_edges(1:end-1)+bin_width/2;
                    for iband = 1:size(fband,1)
                        f1 = fband(iband,1);
                        f2 = fband(iband,2);
        
                        fidx = (beamdata.F>=fband(iband,1))&(beamdata.F<=fband(iband,2));
                        B_incoh = squeeze(sum(B_pow(fidx,:,:)));

                        [B_ele_max,max_idx] = max(B_incoh,[],2);
                        elev_est= beamdata.elev_deg(max_idx);

                        elev_hist(file_idx,:,iband) = single(histcounts(elev_est,hist_param.el_edges,'Normalization','count')); 
                        clear B_incoh B_ele_max

                        toc
                    end
                    disp('Finished processing.')
                end

            end %do stats
            t1 = toc;
            fprintf('File took %1.2f seconds\n\n\n  ',t1)
        end %file_idx

        %%%%Save statistical data and generate histograms
        

        if do_stats
            if ~exist(bf_hist_filename,'file')||overwrite_stats
                disp('Saving beamformer histogram data...')
           
                if ~isfolder(fullfile(savefolder))
                    mkdir(fullfile(savefolder))
                end
    
                if do_processing
                    save(bf_hist_filename,'file_time_utc','hist_param','elev_hist','fband','-v7.3')
                end
                disp('Save complete.')
                toc
            elseif do_histogram_plots
                disp('Loading beamformer histogram data...')
                load(bf_hist_filename,'file_time_utc','hist_param','elev_hist','fband')
            end

        end

        % produce the histogram plots
        if do_histogram_plots 
            t_label = {datestr(time_start_utc,'yyyymmddTHHMMSS') datestr(time_stop_utc,'yyyymmddTHHMMSS')};

            if save_to_ppt
                title_slide = sprintf('Drifter #%i, Acoustic Sphere %i: %s',drifter_num,acoustic_num, vector_sensor);
                subtitle_slide = sprintf('%s - %s',time_start_utc,time_stop_utc);

                pptx.addSlide('Master',1,'Layout','Title Slide');
                pptx.addTextbox(title_slide,'Position','Title');
                pptx.addTextbox(subtitle_slide,'Position','Subtitle');

            end
%             dive_num = find(di==dive_index);
            


            %% elevation histogram
            bin_width = median(diff(hist_param.el_edges));
            el_centers = hist_param.el_edges(1:end-1)+bin_width/2;
            for iband = 1:size(fband,1)

                f1 = fband(iband,1);
                f2 = fband(iband,2);
                
                fprintf('Producing histograms for Deployment %i: freq %1.2fkHz to %1.2fkHz \n',deployment,f1/1e3,f2/1e3)
		        ax = [];
                if do_processing
                    set(groot,'CurrentFigure',el_hist_fig); clf;

                    title_str = {'Array Elevation Histogram',sprintf('Freq Band %1.2fkhz-%1.2fkHz',f1/1e3,f2/1e3)};
                    title_str = cat(2,{sprintf('%s to %s',datestr(time_start_utc),datestr(time_stop_utc))},title_str);
        
                    plotElevationHistogram(file_time_utc,el_centers,elev_hist(:,:,iband))
    
%                     linkaxes(ax,'x');
                    xlim([min(file_time_utc) max(file_time_utc)])
        
                    title('')
                    sgtitle(title_str,'fontsize',14,'fontweight','bold')
        
        
                    if save_to_ppt
                        linkaxes(ax,'x')
                        xlim([min(file_time_utc) max(file_time_utc)])
                        slideId = pptx.addSlide();
                        fprintf('Added slide %d\n',slideId);
                        pptx.addTextbox([title_slide ' ' subtitle_slide sprintf(' %1.0f kHz to %1.0f kHz',f1/1e3,f2/1e3)]);
                        pptx.addPicture(gcf);
                    end
                    if save_figures
                        png_savename = fullfile(sprintf('%1.2fkHz_to_%1.2fkHz_el_hist_%s_%s',f1/1e3,f2/1e3,t_label{1},t_label{2}));
                        saveas(gcf,fullfile(savefolder,[png_savename '.png']))
                        saveas(gcf,fullfile(savefolder,[png_savename '.fig']))
                    end
                    set(groot,'CurrentFigure',el_hist_fig); clf;
                end


            if save_to_ppt
                newFile = pptx.save(fullfile(savefolder,'directional_histograms'));
            end
            
        end
    end
        end
end
