close all, clear all
% this version will load in the deployment log and process each deployment
% within the specified time range. a table of median/mean spectra levels
% will be computed and appended to a table that is saved out each time so
% as not to lose any progress. data will be saved to a specific
% path/filename that is descriptive of all relevant parameters that can be
% adjusted
use_remote = false;
[data_basedir,procdata_basedir,gitpath] = setUpDrifterPaths(use_remote,1);
% data_basedir = '/Volumes/Shared-1/ONR_DRIFTER';
% data_basedir = {'/Volumes/TFOFA23_1','/Volumes/TFO_FA23_D1'};
do_raw_data = true; % process the spectrograms
do_bf_data = false; % bf part still needs to be updated
do_plots = true; % save out each plot as a png and fig file

% limit the data to process to the following:
expt = ''; % process only this experiment
drifters =[]; % process only these drifters
dateset_local = []; % process only between these times
deployments =[34];

overwrite_data = false;

save_plots = true;  % save out figures as png and fig
save_to_ppt = false; % print figures to powerpoint

avg_type = 'Median'; % what type of average accross time do I want ?

% el_plot = [-90:16:90]; % which elevations to plot from beamformer (choose from -90:2:90)

savefolderbase = fullfile(procdata_basedir,mfilename);
if ~isfolder(savefolderbase)
    mkdir(savefolderbase)
end

% the frequency bands to plot for integrated results
fband = [
    1e3 2.5e3
    2.5e3 15e3
    ];

% fft size for the spectrogram calculations
% this will not impact bf results because those are being loaded in from
% preprocessed data
do_resample = true;
fres = 100; % freq resolution in Hz
fs_resample = 55e3;

if do_resample
    fs_spec = fs_resample;
else
    fs_spec = 102400;
end
nfft_spec = 2^nextpow2(fs_spec/fres); %

driftlog = getDeployLog(gitpath);

% downselect to the desired processing set
process_set = true(size(driftlog,1),1);
if ~isempty(deployments)
    process_set = ismember(driftlog.Deployment,deployments);
end
if ~isempty(drifters)
    process_set = ismember(driftlog.DrifterNumber,drifters)&process_set;
end
if ~isempty(expt)
    process_set = process_set&ismember(driftlog.ExperimentName,expt);
end
if ~isempty(dateset_local)
    isintime = deploy_time >= dateset_local(1) & recover_time <= dateset_local(2);
    process_set = process_set&isintime;
end
driftlog = driftlog(process_set,:);

freq = 0:28000;
NL_dB_0 = getWentzWindNoise(0, freq);
NL_dB_3 = getWentzWindNoise(3, freq);
NL_dB_6 = getWentzWindNoise(6, freq);

% start the parallel pool
try
    Nworkers = 4;
    parpool(Nworkers)
end


deployment_set = unique(driftlog.Deployment).';

for deployment = deployment_set
    Ssavefilename = []; Bsavefilename = [];

    if save_to_ppt
        clear pptx pptx_bf
        pptx    = exportToPPTX('../tools/myTemplate.pptx', ...
            'Dimensions',[12 6], ...
            'Title','Long Term Spectra', ...
            'Author','MATLAB', ...
            'Subject','Automatically generated PPTX file', ...
            'Comments','This file has been automatically generated by exportToPPTX');
    
        pptx_bf    = exportToPPTX('../tools/myTemplate.pptx', ...
            'Dimensions',[12 6], ...
            'Title','Beamformer Output', ...
            'Author','MATLAB', ...
            'Subject','Automatically generated PPTX file', ...
            'Comments','This file has been automatically generated by exportToPPTX');
    end


    % get the index of this deployment in the table
    didx = find(driftlog.Deployment==deployment,1,'first');

    t0_utc = driftlog.DeployTimeUTC(didx);
    tend_utc = driftlog.RecoverTimeUTC(didx);
    event_name = driftlog.event_name(didx);


    data_subdir = fullfile(driftlog.ExperimentName{didx},event_name);

    param_spec = sprintf('fs%1.0f_nfft%i',fs_spec,nfft_spec);

    thissavefolder = fullfile(savefolderbase,param_spec,driftlog.ExperimentName{didx});

    if ~isfolder(thissavefolder)
        mkdir(thissavefolder)
    end

    Ssavefilename = fullfile(thissavefolder,sprintf('Spectra_%s',event_name));

    Bsavefilename = fullfile(thissavefolder,sprintf('Beam_Spectra_%s',event_name));

    hx = []; hy = []; hz = []; hp = []; F = [];
    h1 = []; savename = []; beamdata = [];

    % get full path to this data set
    if iscell(data_basedir)
        % more than one base directory has been supplied, we'll want to
        % check them all
        filelist = []; idir = 0;
        for idir=1:length(data_basedir)
            data_dir = fullfile(data_basedir{idir},data_subdir,'AcousticData');
            [filelist,filetimes_utc] = getFilesInRange(data_dir,t0_utc,tend_utc);
            logdir = fullfile(data_basedir{idir},data_subdir,'ControlSystem');
            if ~isempty(filelist)
                break
            end
        end
    else
        data_dir = fullfile(data_basedir,data_subdir,'AcousticData');
        [filelist,filetimes_utc] = getFilesInRange(data_dir,t0_utc,tend_utc);
        logdir = fullfile(data_basedir,data_subdir,'ControlSystem');
    end


    config_file = fullfile(data_dir,driftlog.AcousticConfig{didx});
    acoustic_config = readtable(config_file);
    ch_select = acoustic_config.Channel(~cellfun(@isempty,acoustic_config.sensor_type));

    % % select which processed result to use
    % proc_version = 'run_drifter_processing_v2';
    % array_type = 'line'; fs_bf = 55e3; nfft_bf = 1024; el_res = 2;
    % % procdata_dir = fullfile(procdata_basedir,data_subdir,proc_version,...
    % %     sprintf('%s_fs%1.0f_nfft%1.0f_dEl%i_T%s',array_type,fs_bf,nfft_bf,el_res,...
    % %     datestr(t0,'yyyymmdd_HHMMSS')),'processed_data');
    % procdata_dir = fullfile(procdata_basedir,data_subdir,proc_version,...
    %     sprintf('%s_fs%1.0f_nfft%1.0f_dEl%i',array_type,fs_bf,nfft_bf,el_res),'processed_data');

    % Spow_avg = zeros(length(filelist),nfft_bf/2+1,12);
    % Spow_med = zeros(length(filelist),nfft_bf/2+1,12);
    % b_incoh_avg_dB = zeros(length(filelist),91,size(fband,1));
    % b_incoh_med_dB = zeros(length(filelist),91,size(fband,1));
    % Bpow_avg = zeros(length(filelist),nfft_bf/2+1,91);
    % Bpow_med = zeros(length(filelist),nfft_bf/2+1,91);
    % Tfile = NaT(1,length(filelist));

    process_raw_data = do_raw_data&(~exist([Ssavefilename '.mat'],'file')|overwrite_data);
    process_bf_data = do_bf_data&(~exist([Bsavefilename '.mat'],'file')|overwrite_data);

    % no files were found, we'll skip to the next deployment
    if isempty(filelist)&&(process_raw_data||process_bf_data)
        continue
    end


    if process_raw_data || process_bf_data
        %for ifile = 1:length(filelist)
        Nfiles = length(filelist);
        Spow_avg = zeros(Nfiles,nfft_spec/2+1,length(ch_select));
        Spow_med = zeros(Nfiles,nfft_spec/2+1,length(ch_select));
        F_spec = zeros(Nfiles,nfft_spec/2+1);
        Tfile = NaT(Nfiles,1);
        parfor (ifile = 1:length(filelist),Nworkers) % paralell for loop
            %         for ifile = 1:length(filelist)
            savename = '';
            F = [];
            tic
            fprintf('Deployment %i: processing spectra for file %i of %i\n',deployment,ifile,length(filelist))

            % load in the raw data to get spectrograms?

            if process_raw_data
                wav_filename = fullfile(filelist(ifile).folder,filelist(ifile).name);
                try
                    [y,fs0] = audioread(wav_filename);
                catch
                    warning('Error reading file, skipping file %s',filelist(ifile).name)
                    continue
                end

                if do_resample
                    y = resample(y,fs_spec,fs0);
                end


                [Spow,F_spec(ifile,:),T] = getDrifterSpectrogramV2(y,nfft_spec,[],fs_spec,config_file,'psd');

                % average over time
                Spow_avg(ifile,:,:) = squeeze(mean(Spow,2));
                Spow_med(ifile,:,:) = squeeze(median(Spow,2));

                % if 1 % save as we go
                %     parsaveS(Ssavefilename,Spow_avg,Spow_med,F_spec,fband,Tfile)
                % end

                % if 0
                %     figure
                %     plot(F_spec(:,1)/1e3,10*log10(squeeze(Spow_avg(ifile,:,8)))); grid on; ylim auto
                %     keyboard
                % end
            end

            % load beamformed data? this still needs to be updated,
            % requires saved beamform data

            if process_bf_data

                savename = sprintf('beamformer_data_%s.mat',datestr(filetimes_utc(ifile),'yyyymmddTHHMMSS'));
                beamfile_name = fullfile(procdata_dir,savename);
                file_exists = exist(beamfile_name,'file');
                if file_exists

                    beamdata = load(beamfile_name,'beamdata');
                    beamdata = beamdata.beamdata;
                    beamdata = integrateBandBF(beamdata,fband);
                    % scale to match PSD units
                    % for some reason I thought it was a good idea to not save all
                    % the frequencies ... this is a patch...
                    % F_bf = [0:(nfft_bf/2)]*fs_bf/nfft_bf;
                    % Bpow = zeros(nfft_bf/2+1,length(beamdata.T_utc),91);
                    % [~,fidx] = intersect(F_bf,beamdata.F);
                    % Bpow(fidx,:,:) = 10.^(double(beamdata.B_pow_dB)/10)*(1/(winPow*fs_bf));
                    % Bpow= 10.^(double(beamdata.B_pow_dB)/10)*(1/(winPow*fs_bf));
                    Bpow = beamdata.B_pow*(1/(winPow*fs_bf));
                    df = median(diff(beamdata.F));
                    B_incoh = beamdata.B_incoh*(df/(winPow*fs_bf));

                    Bpow_avg(ifile,:,:) = mean(Bpow,2);
                    Bpow_med(ifile,:,:) = median(Bpow,2);

                    b_incoh_avg_dB(ifile,:,:) = 10*log10(squeeze(mean(B_incoh,1)));
                    b_incoh_med_dB(ifile,:,:) = 10*log10(squeeze(median(B_incoh,1)));
                else
                    fprintf('Deployment %i: BF file %i of %i, %s does not exist!\n',deployment,ifile,length(filelist),savename)
                end
            end
            Tfile(ifile) = filetimes_utc(ifile);

            tdur=toc;

            fprintf('Deployment %i: file %i of %i took %1.2f seconds\n',deployment,ifile,length(filelist),tdur)
        end  %ifile (long ifile loop)

        if process_raw_data
            parsaveS(Ssavefilename,Spow_avg,Spow_med,F_spec(1,:),fband,Tfile)
        end
        if process_bf_data
            el_res = 2;
            elev_deg = -90:el_res:90;
            F_bf = [0:(nfft_bf/2)]*fs_bf/nfft_bf;
            parsaveB(Bsavefilename,Bpow_avg,Bpow_med,b_incoh_avg_dB,b_incoh_med_dB,F_bf,fband,Tfile,elev_deg)
        end
    end  %process_raw_data  || process_bf_data
    %%

    if do_plots
        master_generate_plots;
    end  %do_plots

    close all
    %% Save presentation and close presentation -- overwrite file if it already exists
    % Filename automatically checked for proper extension
    if save_to_ppt&&do_raw_data
        newFile     = pptx.save(fullfile(thissavefolder,'long_term_spectra'));
    end
    if  save_to_ppt&&do_bf_data
        newFile2     = pptx_bf.save(fullfile(thissavefolder,'beamform_output'));
    end
end
delete(gcp('nocreate'))


function parsaveS(fname,Spow_avg,Spow_med,F,fband,Tfile)
save([fname '.mat'], 'Spow_avg','Spow_med','F','fband','Tfile')
end

function parsaveB(fname,Bpow_avg,Bpow_med,b_incoh_avg_dB,b_incoh_med_dB,F,fband,Tfile,elev_deg)
save([fname '.mat'], 'Bpow_avg','Bpow_med','b_incoh_avg_dB','b_incoh_med_dB','F','fband','Tfile','elev_deg')
end

